services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  infra.api:
    image: ${DOCKER_REGISTRY-}infraapi
    build:
      context: .
      dockerfile: Infra.Api/Dockerfile
    depends_on:
      - postgres
    ports:
     - "6000:80"

volumes:
  postgres_data:
  